theme = "onedark_transparent"

[editor]
line-number = "relative"
bufferline = "always"
completion-replace = true

[editor.indent-guides]
render = true
character = "╎"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
display-signature-help-docs = false

# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
C-space = "toggle_comments"
# C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
# "C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
"C-c" = "normal_mode" # Maps Ctrl-c to enter normal mode
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode
