keys:
  # - &sensitive_not_secret age1q9aa6vyf9wt6r3mrl6362j5cn8x48k0567y9hsmuqn807mpln5zqrjfuax
  # new key when ready
  - &sensitive_not_secret age1adxqkgumqhscqk8dkat5hnqx3wzyshfhhqe3jz6xdm5t34yyrdfqejgvtg
  - &users:
    - &kylepzak age1q3mp87y8ddl2x0skpjla8n7cuqr0attzm6ywt3axgrj28ukvy5lqq5l32t
    - &ssh_thinkpad age14hqndcn28shcmyqafh53ykqsz26rs6hre94nfwr9xm5laln8d9qs3mp3lt
    - &ssh_kylepzak age1fepmpsw6v9juhx3nkq5es0mhjs40xtmajn3fl9jxe779flmjh5wq0palxn
    - &bcachefs_test age1l057emzajvutettkmsv8tw86wenxghn3z2aerae07tne9ay0ugkqusz877
    - &test_vm age1gfamaev28ur53f09qllqhs7fqv74yd0unye4yaduhf436cl8usys640ld5
    - &stormjib age1w9jy86ajwzd7e0rszhe80065fuynwnr647wxfx0yn7st0xzqsfsqzgzvxy
    - &cargohold age1vv7x7cupsczqaducs2pxpn7t3mqj5e5jkyc70489fad05rvyga4s57hwan
    - &dinghy age1v96s5f9tqz6xgndsgg5lt2zy8xe6j7k9wxz3k52paw9sena4q3gszjy425
  - &capstans:
    - &ssh_capstan1 age1uatt9h5c3q6grd72skc2k7zzlpam9aregvyeyuzmazw9fpzcysqqwlrh8d
    - &ssh_capstan2 age1exv224uk35dyh933g4uv96rtgw9vztwv8xgd9t3r2tf3ltyfdezqxcauhf
    - &ssh_capstan3 age1gh589ckrhz9c940waqnng3zv58l530ettpd7rg2lv2n7zx3h592s99jux6

creation_rules:
  - path_regex: sensitive/[^/]+\.yaml$
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *sensitive_not_secret

  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *kylepzak
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *bcachefs_test
          - *test_vm
          - *ssh_capstan1
          - *ssh_capstan2
          - *ssh_capstan3
          - *stormjib
          - *cargohold
          - *dinghy

  - path_regex: attic-server/[^/]+\.yaml$
    key_groups:
      - age:
        - *kylepzak
        - *ssh_kylepzak
        - *ssh_thinkpad
        - *ssh_capstan3

  - path_regex: nix-signing/[^/]+\.yaml$
    key_groups:
      - age:
          - *kylepzak
          - *ssh_kylepzak
          - *ssh_thinkpad

  - path_regex: capstan/[^/]+\.yaml$
    # - path: capstan/secrets.enc.yaml
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *ssh_capstan1
          - *ssh_capstan2
          - *ssh_capstan3
          - *test_vm
