keys:
  # - &sensitive_not_secret age1q9aa6vyf9wt6r3mrl6362j5cn8x48k0567y9hsmuqn807mpln5zqrjfuax
  # new key when ready
  - &sensitive_not_secret age1adxqkgumqhscqk8dkat5hnqx3wzyshfhhqe3jz6xdm5t34yyrdfqejgvtg
  - &users:
    - &kylepzak age1q3mp87y8ddl2x0skpjla8n7cuqr0attzm6ywt3axgrj28ukvy5lqq5l32t
    - &ssh_thinkpad age14hqndcn28shcmyqafh53ykqsz26rs6hre94nfwr9xm5laln8d9qs3mp3lt
    - &ssh_kylepzak age1fepmpsw6v9juhx3nkq5es0mhjs40xtmajn3fl9jxe779flmjh5wq0palxn
    - &bcachefs_test age1l057emzajvutettkmsv8tw86wenxghn3z2aerae07tne9ay0ugkqusz877
    - &test_vm age1gfamaev28ur53f09qllqhs7fqv74yd0unye4yaduhf436cl8usys640ld5
    - &stormjib age1zh045acnsrzgqxvlggdultqkq8ksvmuruu92akrsyxq5v6xk54sqn3j0pq
    - &cargohold age1vv7x7cupsczqaducs2pxpn7t3mqj5e5jkyc70489fad05rvyga4s57hwan
    - &dinghy age1v96s5f9tqz6xgndsgg5lt2zy8xe6j7k9wxz3k52paw9sena4q3gszjy425
  - &capstans:
    - &ssh_capstan1 age1katkdmh05xy9n5pmrkaznw0e5j4p96js88dzxy4l0zt06pfa4qzs0gsua5
    - &ssh_capstan2 age1daxggyz58h525ww5clnwwuwxu7tf5mlz8as8n7cy8dhv74u4qcqq0jagrp
    - &ssh_capstan3 age1wwtevxuhkfh6nyl23axkx0s3pnywrw95tj85qrg03fhh6jkmf5nsfknx09
  - &lightships:
    - &ssh_lightship_atx age1csp7a8m4d8gfpeq86wje2ttxw9f66phehlacsuqckrft46s6s4csfjzrsl
  - &lighthouses:
    - &ssh_lighthouse_east age1k393g9cgc0xa88ej05tsppcktrrgsp6efp70hffu3zmzhmkwr4jsgs3lg3
    - &ssh_lighthouse_west age1ex6z7fus35kvm42annhs9spzcmlccn2p7l3ugqdrt6wjee4evdqs9evvm6
    - &ssh_lighthouse_yul1 age1u22wfqweftvgwf0vrszzkagz3w5u5jzsa2y7ez8ap3s7pxngp34sc2t9qj
    - &ssh_lighthouse_yul2 age1mgj529x49h0w28jluaxgkxl3e8dgk9l5d94wt9g7mmgx5e7ylsqsslmsma

creation_rules:
  - path_regex: sensitive/[^/]+\.yaml$
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *sensitive_not_secret

  - path_regex: homes/dotfiles/config$
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *sensitive_not_secret

  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *kylepzak
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *bcachefs_test
          - *test_vm
          - *ssh_capstan1
          - *ssh_capstan2
          - *ssh_capstan3
          - *ssh_lightship_atx
          - *stormjib
          - *cargohold
          - *dinghy

  - path_regex: attic-server/[^/]+\.yaml$
    key_groups:
      - age:
          - *kylepzak
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *ssh_capstan3

  - path_regex: nix-signing/[^/]+\.yaml$
    key_groups:
      - age:
          - *kylepzak
          - *ssh_kylepzak
          - *ssh_thinkpad

  - path_regex: capstan/[^/]+\.yaml$
    # - path: capstan/secrets.enc.yaml
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *ssh_capstan1
          - *ssh_capstan2
          - *ssh_capstan3
          - *test_vm

  - path_regex: thinkpad/[^/]+\.yaml$
    # - path: thinkpad/secrets.enc.yaml
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad

  - path_regex: lightship/[^/]+\.yaml$
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *ssh_lightship_atx

  - path_regex: lighthouse/[^/]+\.yaml$
    # - path: lighthouse/secrets.enc.yaml
    key_groups:
      - age:
          - *ssh_kylepzak
          - *ssh_thinkpad
          - *ssh_lighthouse_yul1
          - *ssh_lighthouse_yul2
